/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaLoteria;

import ModeloLoteria.LoteriaDto;
import VistaPrincipal.Principal;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos
 */
public class ConsultarLoteriaInternalFrame extends javax.swing.JInternalFrame {

    private Principal principal;
    private DefaultTableModel tabla;

    /**
     * Creates new form ConsultarLoteriaInternalFrame
     */
    public ConsultarLoteriaInternalFrame(Principal p) {
        initComponents();
        this.principal = p;
        initComponents();
        this.getContentPane().setBackground(Color.white);

        String tituloTabla[] = {"codigo", "nombre", "dia", "hora","minuto","ruta"};
        this.tabla = new DefaultTableModel(null, tituloTabla);
        this.tableConsulta.setModel(tabla);
        this.OptCodigo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsulta = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        OptCodigo = new javax.swing.JRadioButton();
        OptNombre = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        cmdConsultarTodo = new javax.swing.JButton();

        setTitle("Consultar loteria");

        tableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableConsulta);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valores consulta"));

        OptCodigo.setText("Codigo");
        OptCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptCodigoActionPerformed(evt);
            }
        });

        OptNombre.setText("Nombre");
        OptNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor a buscar");

        txtConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConsultarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultarKeyTyped(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        cmdConsultarTodo.setText("Consultar todo");
        cmdConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsultarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdConsultarTodo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OptCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(OptNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptCodigo)
                    .addComponent(OptNombre))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnConsultar)
                    .addComponent(cmdConsultarTodo))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OptCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptCodigoActionPerformed
        // TODO add your handling code here:
        this.OptNombre.setSelected(false);
        this.txtConsultar.setText("");
    }//GEN-LAST:event_OptCodigoActionPerformed

    private void OptNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptNombreActionPerformed
        // TODO add your handling code here:
        this.OptCodigo.setSelected(false);
        this.txtConsultar.setText("");
    }//GEN-LAST:event_OptNombreActionPerformed

    private void txtConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.consultarLoteria();
        }
    }//GEN-LAST:event_txtConsultarKeyPressed

    public void consultarTodoLoteria() {
        ArrayList<LoteriaDto> lista = new ArrayList();
        this.tabla.setRowCount(0);
        this.tabla.fireTableDataChanged();

        lista = this.principal.getFachada().listarLoterias();
        this.adicionarATabla(lista);
    }

    public void consultarLoteria() {
        ArrayList<LoteriaDto> lista = new ArrayList();

        if (this.txtConsultar.getText().equals("")) {
            return;
        }

        this.tabla.setRowCount(0);
        this.tabla.fireTableDataChanged();
        if (this.OptCodigo.isSelected()) {
            int codigo = Integer.parseInt(this.txtConsultar.getText());
            lista = this.principal.getFachada().listarLoteriaXCodigo(codigo);
        }
        if (this.OptNombre.isSelected()) {
            String nombre = this.txtConsultar.getText();
            lista = this.principal.getFachada().listarLoteriaXNombre(nombre);
        }

        this.adicionarATabla(lista);

    }

    private void adicionarATabla(ArrayList<LoteriaDto> lista) {
        String registro[] = new String[6];

        for (LoteriaDto dto : lista) {

            registro[0] = dto.getCodigo() + "";
            registro[1] = dto.getNombre() + "";
            registro[2] = dto.getDiaFormato() + "";
            registro[3] = dto.getHora() + "";
            registro[4] = dto.getMinuto() + "";
            registro[5] = dto.getRuta() + "";
            this.tabla.addRow(registro);
            this.tabla.fireTableDataChanged();

        }
    }

    private void txtConsultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();
        if (this.OptCodigo.isSelected()) {
            if (num < '0' || num > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtConsultarKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        this.consultarLoteria();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableConsultaMouseClicked
        // TODO add your handling code here:
        if (this.tableConsulta.getSelectedRow() >= 0) {

            int seleccion = this.ventana();
            if (seleccion == 0) {

                int codigo = Integer.parseInt(this.tableConsulta.getValueAt(this.tableConsulta.getSelectedRow(), 0).toString());

                boolean valor = this.principal.getFachada().eliminarLoteria(codigo);
                if (valor) {

                    this.tabla.removeRow(this.tableConsulta.getSelectedRow());

                } else {
                    JOptionPane.showMessageDialog(null, "existe un error al eliminar la loteria debido a que esta ya tiene\n"
                            + "planes de loteria registrados");

                }
            }
        }
    }//GEN-LAST:event_tableConsultaMouseClicked

    private void cmdConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsultarTodoActionPerformed
        // TODO add your handling code here:
        this.consultarTodoLoteria();
    }//GEN-LAST:event_cmdConsultarTodoActionPerformed

    private void txtConsultarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyReleased
        // TODO add your handling code here:
          String cadena = (this.txtConsultar.getText()).toUpperCase();
        this.txtConsultar.setText(cadena);
    }//GEN-LAST:event_txtConsultarKeyReleased

    private int ventana() {
        int seleccion = JOptionPane.showOptionDialog(
                rootPane,
                "desea eliminar la loteria ",
                "Selector de opciones ",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{" si", "Cancelar"},
                "opcion 1");
        return seleccion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OptCodigo;
    private javax.swing.JRadioButton OptNombre;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton cmdConsultarTodo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableConsulta;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
