/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaTipoPremio;

import ModeloLoteria.LoteriaDto;
import ModeloTipoPremio.TipoPremioDto;
import VistaPrincipal.Principal;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class RegistrarTipoPremioInternalFrame extends javax.swing.JInternalFrame {

    private Principal principal;
    private int tipoAnterior;

    /**
     * Creates new form RegistrarTipoPremioInternalFrame
     */
    public RegistrarTipoPremioInternalFrame(Principal p) {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.principal = p;
    }

    public void deshabilitarCampos() {
        this.txtNombre.setEnabled(false);
        this.txtValorPesos.setEnabled(false);
        this.txtValorBolivares.setEnabled(false);
        this.cmdHabilitar.setEnabled(false);
        this.cmdModificar.setEnabled(false);
    }

    public void habilitarCampos() {
        this.txtNombre.setEnabled(true);
        this.txtValorPesos.setEnabled(true);
        this.txtValorBolivares.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTipoPremio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtValorPesos = new javax.swing.JTextField();
        txtValorBolivares = new javax.swing.JTextField();
        cmdRegistrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmdHabilitar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();

        setTitle("Registrar tipo premio");

        jLabel1.setText("Tipo premio:");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Valor pesos: ");

        jLabel4.setText("Valor bolivares");

        txtTipoPremio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTipoPremioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoPremioKeyTyped(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtValorPesos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorPesosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPesosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorPesosKeyTyped(evt);
            }
        });

        txtValorBolivares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorBolivaresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorBolivaresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorBolivaresKeyTyped(evt);
            }
        });

        cmdRegistrar.setText("Registrar");
        cmdRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarActionPerformed(evt);
            }
        });
        cmdRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdRegistrarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmdRegistrarKeyReleased(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmdHabilitar.setText("Habilitar");
        cmdHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHabilitarActionPerformed(evt);
            }
        });

        cmdModificar.setText("Modiifcar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdHabilitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorBolivares, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorBolivares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdRegistrar)
                    .addComponent(jButton2)
                    .addComponent(cmdHabilitar)
                    .addComponent(cmdModificar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTipoPremioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoPremioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ArrayList<TipoPremioDto> lista = this.principal.getFachada().listarTipoPremioXTipo(Integer.parseInt(this.txtTipoPremio.getText()));
            if (!lista.isEmpty()) {
                int tipo = Integer.parseInt(this.txtTipoPremio.getText());

                for (TipoPremioDto p : lista) {
                    this.tipoAnterior = p.getTipo();

                    this.txtTipoPremio.setText(p.getTipo() + "");
                    this.txtNombre.setText(p.getNombre() + "");
                    this.txtValorBolivares.setText(p.getValorBolivaresFormato() + "");
                    this.txtValorPesos.setText(p.getValorPesosFormato() + "");
                }
                this.deshabilitarCampos();
                this.cmdHabilitar.setEnabled(true);
            } else {
                this.vaciarCamposBusqueda();
                this.cmdHabilitar.setEnabled(false);
                this.cmdModificar.setEnabled(false);
                this.habilitarCampos();
                this.txtNombre.requestFocus();
            }
        }
    }//GEN-LAST:event_txtTipoPremioKeyPressed

    private void txtTipoPremioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoPremioKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();

        if (num < '0' || num > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTipoPremioKeyTyped

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.txtValorBolivares.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtValorPesosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPesosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.registrar();
        }
    }//GEN-LAST:event_txtValorPesosKeyPressed

    /**
     * retorna verdadero si existe un campo vacio y falso si todos estan llenos
     *
     * @return
     */
    private boolean validarCampos() {
        return (this.txtTipoPremio.getText().isEmpty() || this.txtNombre.getText().isEmpty() || this.txtValorBolivares.getText().isEmpty() || this.txtValorPesos.getText().isEmpty());
    }

    private void registrar() {
        if (!this.validarCampos()) {

            TipoPremioDto dto = new TipoPremioDto();
            dto.setTipo(Integer.parseInt(this.txtTipoPremio.getText()));
            dto.setNombre(this.txtNombre.getText());
            String bolivares = this.txtValorBolivares.getText().replace(".", "");
            String pesos = this.txtValorPesos.getText().replace(".", "");
            dto.setValorBolivares(Integer.parseInt(bolivares));
            dto.setValorPesos(Integer.parseInt(pesos));
            boolean valor = this.principal.getFachada().registrarTipoPremio(dto);
            if (valor) {
                JOptionPane.showMessageDialog(null, "el tipo premio se registro exitosamente");
                this.deshabilitarCampos();
                this.vaciarCampos();
                return;
            }
            JOptionPane.showMessageDialog(null, "el tipo premio ya se encuentra registrado");
        } else {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");
        }
    }

    public void vaciarCampos() {
        this.txtNombre.setText("");
        this.txtTipoPremio.setText("");
        this.txtValorBolivares.setText("");
        this.txtValorPesos.setText("");
    }

    private void vaciarCamposBusqueda() {
        this.txtNombre.setText("");
        this.txtValorBolivares.setText("");
        this.txtValorPesos.setText("");
    }

    private void txtValorBolivaresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorBolivaresKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.txtValorPesos.requestFocus();
        }
    }//GEN-LAST:event_txtValorBolivaresKeyPressed

    private void txtValorBolivaresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorBolivaresKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();

        if (num < '0' || num > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorBolivaresKeyTyped

    private void txtValorPesosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPesosKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();

        if (num < '0' || num > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorPesosKeyTyped

    private void cmdRegistrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdRegistrarKeyPressed
        // TODO add your handling code here:
        this.registrar();
    }//GEN-LAST:event_cmdRegistrarKeyPressed

    private void cmdHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHabilitarActionPerformed
        // TODO add your handling code here:
        this.habilitarCampos();
        this.cmdModificar.setEnabled(true);
    }//GEN-LAST:event_cmdHabilitarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:
        this.modificar();
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdRegistrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdRegistrarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdRegistrarKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        String cadena = (this.txtNombre.getText()).toUpperCase();
        this.txtNombre.setText(cadena);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void cmdRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarActionPerformed
        // TODO add your handling code here:
        this.registrar();
    }//GEN-LAST:event_cmdRegistrarActionPerformed

    private void txtValorBolivaresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorBolivaresKeyReleased
        // TODO add your handling code here:
        if (!this.txtValorBolivares.getText().isEmpty()) {
            NumberFormat formatoNumero = NumberFormat.getNumberInstance();
            String cadena = this.txtValorBolivares.getText().replace(".", "");
            this.txtValorBolivares.setText(formatoNumero.format(Integer.parseInt(cadena)));
        }
    }//GEN-LAST:event_txtValorBolivaresKeyReleased

    private void txtValorPesosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPesosKeyReleased
        // TODO add your handling code here:
        if (!this.txtValorPesos.getText().isEmpty()) {
            NumberFormat formatoNumero = NumberFormat.getNumberInstance();
            String cadena = this.txtValorPesos.getText().replace(".", "");
            this.txtValorPesos.setText(formatoNumero.format(Integer.parseInt(cadena)));
        }
    }//GEN-LAST:event_txtValorPesosKeyReleased

    private void modificar() {
        if (this.validarCampos()) {
            JOptionPane.showMessageDialog(null, "no puede dejar campos vacios");
            return;
        }
        TipoPremioDto dto = new TipoPremioDto();
        dto.setTipo(Integer.parseInt(this.txtTipoPremio.getText()));

        dto.setNombre(this.txtNombre.getText());
        String bolivares = this.txtValorBolivares.getText().replace(".", "");
        String pesos = this.txtValorPesos.getText().replace(".", "");
        dto.setValorBolivares(Integer.parseInt(bolivares));
        dto.setValorPesos(Integer.parseInt(pesos));
        boolean valor = this.principal.getFachada().modificarTipoPremio(this.tipoAnterior, dto);
        if (valor) {
            JOptionPane.showMessageDialog(null, "Modificacion exitosa");

            this.vaciarCampos();
            this.deshabilitarCampos();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdHabilitar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipoPremio;
    private javax.swing.JTextField txtValorBolivares;
    private javax.swing.JTextField txtValorPesos;
    // End of variables declaration//GEN-END:variables
}
