/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaInformeGeneral;

import VistaPrincipal.Principal;
import java.awt.Color;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class VistaInformeGeneralVenta extends javax.swing.JInternalFrame {

    private Principal principal;

    /**
     * Creates new form VistaInformeGeneral
     */
    public VistaInformeGeneralVenta(Principal p) {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.principal = p;
        this.dateFechaF.setDate(new Date());
        this.dateFechaI.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateFechaI = new com.toedter.calendar.JDateChooser();
        dateFechaF = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        colombia1 = new javax.swing.JButton();
        venezuela1 = new javax.swing.JButton();

        setTitle("Reporte general ventas rango de fecha");

        jLabel1.setText("Fecha inicial: ");

        jLabel2.setText("Fecha final: ");

        jButton1.setText("Rerporte general ventas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        colombia1.setText("Rerporte general ventas colombia");
        colombia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colombia1ActionPerformed(evt);
            }
        });

        venezuela1.setText("Rerporte general ventas venezuela");
        venezuela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venezuela1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colombia1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(venezuela1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateFechaF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateFechaI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(colombia1)
                        .addComponent(venezuela1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.guardarArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void colombia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colombia1ActionPerformed
        // TODO add your handling code here:
        this.guardarArchivoNacionalidad("COLOMBIA");
    }//GEN-LAST:event_colombia1ActionPerformed

    private void venezuela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venezuela1ActionPerformed
        // TODO add your handling code here:
        this.guardarArchivoNacionalidad("VENEZUELA");
    }//GEN-LAST:event_venezuela1ActionPerformed

    private void guardarArchivoNacionalidad(String nacionalidad) {

        
        
         SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        if (this.dateFechaF.getDate().compareTo(this.dateFechaI.getDate()) < 0) {
            JOptionPane.showMessageDialog(null, "la fecha inicial no puede ser mayor a la fecha final");

        } else {
           boolean resultado = false;
       
        String fechaInicial = formato.format(this.dateFechaI.getDate());
        String fechaFinal = formato.format(this.dateFechaF.getDate());
        resultado = this.principal.getFachada().generarInformeGeneralNacionalidad(fechaInicial, fechaFinal,"",nacionalidad);

        if (resultado) {
            JOptionPane.showMessageDialog(null,
                    "El archivo se ha guardado Exitosamente",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "ya existe un documento con ese nombre \n el documento esta en uso");
        }
        }
        
        
        
        
        
        
       
    }

    private void guardarArchivo() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        if (this.dateFechaF.getDate().compareTo(this.dateFechaI.getDate()) < 0) {
            JOptionPane.showMessageDialog(null, "la fecha inicial no puede ser mayor a la fecha final");

        } else {
            boolean resultado = false;
            String fechaI;
            String fechaF;
            fechaI = formato.format(this.dateFechaI.getDate());
            fechaF = formato.format(this.dateFechaF.getDate());
        
            resultado = this.principal.getFachada().generarPdfVentasGeneral("", fechaI, fechaF);
                     
            if (resultado) {
                JOptionPane.showMessageDialog(null,
                        "El archivo se ha guardado Exitosamente",
                        "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "ya existe un documento con ese nombre \n el documento esta en uso");
            }
        }
    }
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colombia1;
    private com.toedter.calendar.JDateChooser dateFechaF;
    private com.toedter.calendar.JDateChooser dateFechaI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton venezuela1;
    // End of variables declaration//GEN-END:variables
}
