/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaVenta;

import ModeloVentas.PersonaDto;
import ModeloVentas.VentaDto;
import VistaPrincipal.Principal;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class RegistrarSaldosInicialesInternalFrame extends javax.swing.JInternalFrame {

    private Principal principal;

    /**
     * Creates new form RegistrarSaldosInicialesInternalFrame
     */
    public RegistrarSaldosInicialesInternalFrame(Principal p) {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.principal = p;
        this.cargarComboEmpleados();
        Calendar now = Calendar.getInstance();
        this.txtAño.setText(now.get(Calendar.YEAR) + "");

    }

    private void cargarComboEmpleados() {
        TextAutoCompleter text = new TextAutoCompleter(this.txtCodigo);
        ArrayList<PersonaDto> lista = this.principal.getFachada().listarPersonas();
        for (PersonaDto dto : lista) {
            text.addItem(dto.getCodigoNombre() + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtAño = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        cmbMes = new javax.swing.JComboBox();
        cmbMoneda = new javax.swing.JComboBox();

        setTitle("Registrar saldos iniciales");

        jLabel1.setText("Año: ");

        jLabel2.setText("Mes:");

        jLabel3.setText("Codigo:");

        jLabel4.setText("Saldo:");

        jLabel5.setText("Moneda:");

        jButton1.setText("Registrar saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAñoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAñoKeyTyped(evt);
            }
        });

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSaldoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSaldoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMesKeyPressed(evt);
            }
        });

        cmbMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bolivares", "Pesos" }));
        cmbMoneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMonedaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txtAño)
                    .addComponent(cmbMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyTyped
        int num = evt.getKeyChar();

        if (num < '0' || num > '9') {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();

        if (num < '0' || num > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void txtAñoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAñoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.cmbMes.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoKeyPressed

    private void cmbMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCodigo.requestFocus();
        }
    }//GEN-LAST:event_cmbMesKeyPressed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.cmbMoneda.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void cmbMonedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMonedaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.txtSaldo.requestFocus();
        }
    }//GEN-LAST:event_cmbMonedaKeyPressed

    private void txtSaldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.registrarSaldoInicial();
            this.txtAño.requestFocus();
        }
    }//GEN-LAST:event_txtSaldoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.registrarSaldoInicial();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSaldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyReleased
        // TODO add your handling code here:
        if (!this.txtSaldo.getText().isEmpty()) {
            NumberFormat formatoNumero = NumberFormat.getNumberInstance();
            String cadena = this.txtSaldo.getText().replace(".", "");
            this.txtSaldo.setText(formatoNumero.format(Integer.parseInt(cadena)));
        }
    }//GEN-LAST:event_txtSaldoKeyReleased

    private void registrarSaldoInicial() {
        VentaDto venta = new VentaDto();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        String fecha = formato.format(new Date());
        venta.setFecha(fecha);
        PersonaDto persona = new PersonaDto();
        persona.setCodigoNombre(this.txtCodigo.getText());
        boolean validar = validarPersona(persona);
        if (validar) {
            JOptionPane.showMessageDialog(null, "No existe una persona con ese codigo");
            return;
        }
        venta.setPersona(persona);
        venta.setMoneda(this.cmbMoneda.getSelectedItem().toString());
        String saldo = this.txtSaldo.getText().replace(".", "");
        venta.setSaldoAnterio(Integer.parseInt(saldo));
        int año = Integer.parseInt(this.txtAño.getText());
        int mes = principal.getFachada().generarMes(this.cmbMes.getSelectedItem().toString());
        boolean valor = this.principal.getFachada().registrarSaldoInicial(venta, año, mes);
        if (valor) {
            JOptionPane.showMessageDialog(null, "El saldo se registro correctamente");
            this.vaciarCampos();
            this.txtAño.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "ese codigo de vendedor ya  esta registrado con ese saldo inicial\n"
                    + "en la moneda especificada");
        }

    }

    private boolean validarPersona(PersonaDto dto) {
        ArrayList<PersonaDto> lista = principal.getFachada().listarPersonaXCodigo(dto.getCodigo());
        return lista.isEmpty();
    }

    private void vaciarCampos() {
        this.txtCodigo.setText("");
        this.txtSaldo.setText("");
    }

    private int convertirMes() {
        String mes = this.cmbMes.getSelectedItem().toString();
        if (mes.equalsIgnoreCase("Enero")) {
            return 1;
        }
        if (mes.equalsIgnoreCase("Febrero")) {
            return 2;
        }
        if (mes.equalsIgnoreCase("Marzo")) {
            return 3;
        }
        if (mes.equalsIgnoreCase("Abril")) {
            return 4;
        }
        if (mes.equalsIgnoreCase("Mayo")) {
            return 5;
        }
        if (mes.equalsIgnoreCase("Junio")) {
            return 6;
        }
        if (mes.equalsIgnoreCase("Julio")) {
            return 7;
        }
        if (mes.equalsIgnoreCase("Agosto")) {
            return 8;
        }
        if (mes.equalsIgnoreCase("Septiembre")) {
            return 9;
        }
        if (mes.equalsIgnoreCase("Octubre")) {
            return 10;
        }
        if (mes.equalsIgnoreCase("Noviembre")) {
            return 11;
        }
        if (mes.equalsIgnoreCase("Diciembre")) {
            return 12;
        }
        return 0;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JComboBox cmbMoneda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
