/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaPersonal;

import ModeloVentas.PersonaDto;
import VistaPrincipal.Principal;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ConsultarPersonaInternalFrame extends javax.swing.JInternalFrame {

    private Principal principal;
    private DefaultTableModel tabla;

public ConsultarPersonaInternalFrame(Principal aThis) {
        initComponents();
         this.getContentPane().setBackground(Color.white);
        this.principal = aThis;
        String tituloTabla[] = {"cedula", "codigo", "nombre", "apellido", "direccion", "telefono", "tipo", "activo", "porcentaje","Nacionalidad"};
        this.tabla = new DefaultTableModel(null, tituloTabla);
        this.tableConsulta.setModel(tabla);
        this.OptCedula.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsulta = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        OptCedula = new javax.swing.JRadioButton();
        OptCodigo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        cmdConsultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Consultar persona");

        tableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableConsulta);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valores de consulta"));

        OptCedula.setText("Cedula");
        OptCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptCedulaActionPerformed(evt);
            }
        });

        OptCodigo.setText("Codigo");
        OptCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptCodigoActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor a buscar");

        txtConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConsultarKeyTyped(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        cmdConsultar.setText("Consultar todos");
        cmdConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdConsultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OptCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OptCodigo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptCedula)
                    .addComponent(OptCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar)
                    .addComponent(cmdConsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyTyped
        // TODO add your handling code here:
        int num = evt.getKeyChar();

        if (num < '0' || num > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtConsultarKeyTyped

    private void txtConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.consultarPersona();
        }
    }//GEN-LAST:event_txtConsultarKeyPressed

    private void OptCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptCedulaActionPerformed
        // TODO add your handling code here:
        this.OptCodigo.setSelected(false);
    }//GEN-LAST:event_OptCedulaActionPerformed

    private void OptCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptCodigoActionPerformed
        // TODO add your handling code here:
        this.OptCedula.setSelected(false);
    }//GEN-LAST:event_OptCodigoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        this.consultarPersona();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableConsultaMouseClicked
        // TODO add your handling code here:
            if (this.tableConsulta.getSelectedRow() >= 0) {

            int seleccion = this.ventana();
            if (seleccion == 0) {
               
                int cedula = Integer.parseInt(this.tableConsulta.getValueAt(this.tableConsulta.getSelectedRow(), 0).toString());
                
                boolean valor = this.principal.getFachada().eliminarPersona(cedula);
                if (valor) {
                    
                    this.tabla.removeRow(this.tableConsulta.getSelectedRow());

                } else {
                    JOptionPane.showMessageDialog(null, "existe un error al eliminar persona debido a que esta ya tiene\n"
                            + "registrado ventas");

                }
            }
        }
    }//GEN-LAST:event_tableConsultaMouseClicked

    private void cmdConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsultarActionPerformed
        // TODO add your handling code here:
        this.consultarTodasPersonas();
    }//GEN-LAST:event_cmdConsultarActionPerformed

      private int ventana() {
        int seleccion = JOptionPane.showOptionDialog(
                rootPane,
                "desea eliminar la persona ",
                "Selector de opciones ",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.CANCEL_OPTION,
                null,
                new Object[]{" Si", "Cancelar"},
                "opcion 1");
        return seleccion;
    }
      
      public void consultarTodasPersonas(){
        ArrayList<PersonaDto> lista = new ArrayList();
       
        this.tabla.setRowCount(0);
        this.tabla.fireTableDataChanged();
       lista=this.principal.getFachada().listarPersonas();

     this.adicionarATabla(lista);
      }
      
    public void consultarPersona() {
        ArrayList<PersonaDto> lista = new ArrayList();

        if (this.txtConsultar.getText().equals("")) {
            return;
        }

        int valor = Integer.parseInt(this.txtConsultar.getText());
        this.tabla.setRowCount(0);
        this.tabla.fireTableDataChanged();
        if (this.OptCedula.isSelected()) {
            lista = this.principal.getFachada().listarPersonaXCedula(valor);
        }
        if (this.OptCodigo.isSelected()) {
            lista = this.principal.getFachada().listarPersonaXCodigo(valor);
        }

     this.adicionarATabla(lista);

    }
    
    private void adicionarATabla(ArrayList<PersonaDto> lista){
       String registro[] = new String[10];
        for (PersonaDto dto : lista) {
            registro[0] = dto.getNuip() + "";
            registro[1] = dto.getCodigo() + "";
            registro[2] = dto.getNombre() + "";
            registro[3] = dto.getApellido() + "";
            registro[4] = dto.getDireccion() + "";
            registro[5] = dto.getTelefono() + "";
            registro[6] = this.acomodarTipo(dto.getTipo()) + "";
            registro[7] = this.acomodarActivo(dto.getActivo()) + "";
            registro[8] = dto.getPorcentaje() + "";
            registro[9]=dto.getNacionalidad()+"";

            this.tabla.addRow(registro);
            this.tabla.fireTableDataChanged();

        }
    }
    
     private String acomodarTipo(String tipo){
    if(tipo.equals("V")){
    return "Vendedor";
    }
    if(tipo.equals("P")){
    return "Promotor";
    }
    if(tipo.equals("A")){
    return "Administrativo";
    }
    return null;
    }
    
    
    private String acomodarActivo(String activo){
          if(activo.equals("S")){
    return "Si";
    }
    if(activo.equals("N")){
    return "No";
    }
    return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OptCedula;
    private javax.swing.JRadioButton OptCodigo;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton cmdConsultar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableConsulta;
    private javax.swing.JTextField txtConsultar;
    // End of variables declaration//GEN-END:variables
}
